### ISSUE TITLE
Can't build from AUR

### ISSUE THREAD

**Issue by Joan31** [mruby-zest/mruby-zest-build#25]
Hi,

I'm trying to install Zyn Fusion, but when it build the dependecie mruby-zest-build, I have this trouble :

```
/usr/bin/ld : /tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):/tmp/makepkg/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/src/nvg_context.c:217 : définitions multiples de « mrb_nvg_context_type »; /tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/tmp/makepkg/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293 : défini pour la première fois ici
collect2: erreur: ld a retourné le statut de sortie 1
/usr/bin/ld : /tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):/tmp/makepkg/zyn-fusion/src/mruby-zest-build/deps/mruby-nanovg/src/nvg_context.c:217 : définitions multiples de « mrb_nvg_context_type »; /tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/tmp/makepkg/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293 : défini pour la première fois ici
collect2: erreur: ld a retourné le statut de sortie 1
rake aborted!
Command failed with status (1): [gcc -Wl,-O1,--sort-common,--as-needed,-z,r...]
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:31:in `_run'
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:36:in `rescue in _run'
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:32:in `_run'
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:183:in `run'
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:72:in `block (4 levels) in <top (required)>'
Caused by:
Command failed with status (1): ["gcc" -Wl,-O1,--sort-common,--as-needed,-z...]
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:33:in `_run'
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:183:in `run'
/tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:72:in `block (4 levels) in <top (required)>'
Tasks: TOP => default => all => /tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/bin/mruby => /tmp/makepkg/zyn-fusion/src/mruby-zest-build/mruby/build/host/bin/mruby
(See full trace by running task with --trace)
make: *** [Makefile:13 : all] Erreur 1
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…
Error making: zyn-fusion
```

Do you have a solution ?

Thank you

**Comment by BrunoVernay** [comment]
Same in Fedora (RPM):

```
/usr/share/ruby/fileutils.rb:426: warning: The called method `cp' is defined here
CC    mrbgems/mruby-bin-mruby/tools/mruby/mruby.c -> build/host/mrbgems/mruby-bin-mruby/tools/mruby/mruby.o
LD    build/host/bin/mruby 
/usr/bin/ld: /home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: multiple definition of `mrb_nvg_context_type'; /home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):(.data.rel.ro.local+0x0): first defined here
collect2: error: ld returned 1 exit status
/usr/bin/ld: /home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: multiple definition of `mrb_nvg_context_type'; /home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):(.data.rel.ro.local+0x0): first defined here
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -L/home/bruno2/l/dev/zyn-fusion-build/...]
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:31:in `_run'
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:36:in `rescue in _run'
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:32:in `_run'
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:210:in `run'
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/Rakefile:79:in `block (4 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
Command failed with status (1): [gcc -L/home/bruno2/l/dev/zyn-fusion-build/...]
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:33:in `_run'
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/lib/mruby/build/command.rb:210:in `run'
/home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/Rakefile:79:in `block (4 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => all => /home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/bin/mruby => /home/bruno2/l/dev/zyn-fusion-build/mruby-zest-build/mruby/build/host/bin/mruby
(See full trace by running task with --trace)
make: *** [Makefile:13: all] Error 1
ERROR: 'make' failed

```

**Comment by deepsummersee** [comment]
Same issue happens when building Zest with MinGW64 on Windows 10 as detailed [https://github.com/zynaddsubfx/zyn-fusion-build/issues/52#issuecomment-629843470](here.)

**Comment by apoorv569** [comment]
I'm trying to build zyn-fusion from the AUR, but it fails after some time and gives this output

`ar: creating /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host-debug/lib/libmruby.a
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:45: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/fileutils.rb:595: warning: The called method `rm_f' is defined here
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:46: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/fileutils.rb:426: warning: The called method `cp' is defined here
CC    mrbgems/mruby-bin-mruby/tools/mruby/mruby.c -> build/host/mrbgems/mruby-bin-mruby/tools/mruby/mruby.o
LD    build/host/bin/mruby 
/usr/bin/ld: /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):(.data.rel.ro.local+0x0): multiple definition of `mrb_nvg_context_type'; /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: first defined here
collect2: error: ld returned 1 exit status
/usr/bin/ld: /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(nvg_context.o):(.data.rel.ro.local+0x0): multiple definition of `mrb_nvg_context_type'; /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/lib/libmruby.a(gem.o):/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/src/mruby-widget-lib/src/gem.c:293: first defined here
collect2: error: ld returned 1 exit status
rake aborted!
Command failed with status (1): [gcc -Wl,-O1,--sort-common,--as-needed,-z,r...]
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:31:in `_run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:36:in `rescue in _run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:32:in `_run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:183:in `run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:72:in `block (4 levels) in <top (required)>'

Caused by:
Command failed with status (1): ["gcc" -Wl,-O1,--sort-common,--as-needed,-z...]
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:33:in `_run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/tasks/mruby_build_commands.rake:183:in `run'
/home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/Rakefile:72:in `block (4 levels) in <top (required)>'
Tasks: TOP => default => all => /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/bin/mruby => /home/apoorv/.cache/yay/zyn-fusion/src/mruby-zest-build/mruby/build/host/bin/mruby
(See full trace by running task with --trace)
make: *** [Makefile:13: all] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: zyn-fusion
`
please help, as i really in need for this plugin my projects depends on this plugin.

**Comment by fundamental** [comment]
Looks like this is the result of the -fno-common flag in gcc starting with gcc 10 (I have a gcc 9.x.x on my system). https://gcc.gnu.org/gcc-10/porting_to.html provides a bit of info. It should be a quick fix that I should be able to help guide where the problem would be, though I'd need to get a VM setup to confirm/fix myself.

**Comment by filip-hejsek** [comment]
The problematic definition is this: https://github.com/mruby-zest/mruby-zest-build/blob/b8c3fc29ed31685c02b12634f9e22b7df79ff60e/src/mruby-widget-lib/src/gem.c#L293
It conflicts with this one: https://github.com/mruby-zest/mruby-nanovg/blob/d7d4e1ce434131babb5fd6026201011f5b0b50ea/src/nvg_context.c#L217
What would be the correct fix, change it to `extern const`? (I don't know C/C++ very well)

**Comment by nadiadavis** [comment]
I can confirm that @filip-hejsek's solution fixes the build, and I was able to install on Arch Linux by installing the necessary dependencies, running `git clone https://aur.archlinux.org/zyn-fusion.git && cd zyn-fusion` `makepkg --nobuild`, then patching the line manually, and running `makepkg --noextract --install`

**Comment by Joan31** [comment]
@filip-hejsek and @nadiadavis I can confirme, the solution work.

Just change on **mruby-zest-build/src/mruby-widget-lib/src/gem.c** (line 293):

`const struct mrb_data_type mrb_nvg_context_type;`

to

`extern const struct mrb_data_type mrb_nvg_context_type;`

And it work.

**Comment by apoorv569** [comment]
yep, @filip-hejsek @fundamental  and @Joan31 its working now by the that line. 
thanx :smiley:

**Comment by BrunoVernay** [comment]
I can confirm that adding `extern` to on `mruby-zest-build/src/mruby-widget-lib/src/gem.c` (line 293)
solves the issue on Fedora 32.

**Comment by Famiu** [comment]
I can confirm as well on Arch Linux
